---
title: "Lista 2 - MAE0127 -  Prof Julio Singer"
author: 
 - Alexandre Felix da Silva 11221435 Eduardo Janotti Cavalcanti 11221481
 - Emanuel Hark Maciel 11221380 Emerson Silva Aragão 11371583 Guilherme Yukio Iasunaga 11218195
 - Pedro Henrique Gallo Andrade 11221550 William Silva Veçoso 10801513
date: "16/04/2020"
output:
  pdf_document: 
    latex_engine: xelatex
header-includes:
- \usepackage{graphicx}
- \usepackage[utf8]{inputenc}
- \usepackage{amssymb}
- \usepackage{amsmath}
- \usepackage{float}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lista 2

## Capítulo 3

### Exercício 33

Com a finalidade de entender a diferença entre “desvio padrão” e “erro
padrão”,

a) Simule 1000 dados de uma distribução normal com média 12 e
desvio padrão 4. Construa o histograma correspondente e calcule
a média e o desvio padrão amostrais.

#### Resolução

b) Simule 500 amostras de tamanho n = 4 dessa população. Calcule
a média amostral de cada amostra, construa o histograma dessas
médias e estime o correspondente desvio padrão (que é o erro
padrâo da média).

#### Resolução

c) Repite os passos a) e b) com amostras de tamanhos n = 9 e
n = 16. Comente os resultados.

#### Resolução

d) Repita os passos a) - c) simulando amostras de uma distribuição
qui-quadrado com 3 graus de liberdade.

#### Resolução

## Capítulo 4

### Exercício 1

Considere o conjunto de dados disponível no arquivo \textit{empresa}. Compare as distribuições de frequências de cada variável para indivíduos residentes na capital, interior e outros.

#### Resolução

### Exercício 4

Considere o conjunto de dados disponível no arquivo \textit{coronarias}.

a) Construa um gráfico QQ para comparar as variáveis "Colesterol com medicamento" e "Colesterol sem medicamento" e discuta o resultado.
  
#### Resolução

b) Calcule o coeficiente de correlação de Pearson e o coeficiente de correlação de Spearman entre as variáveis “Altura” e “Peso”.
  
#### Resolução

c) Construa uma tabela de contingência para avaliar a distribuição conjunta das variáveis “Tabagismo” (com 4 nı́veis) e “Arteriopatia” (com 4 nı́veis) e calcule a intensidade de associação entre elas utilizando a estatı́stica de Pearson, o coeficiente de contingência de Pearson e o coeficiente de “Tschuprov”.
  
#### Resolução

### Exercício 5

Considere o conjunto de dados disponível no arquivo \text{esforço}.

a) Compare as distribuições de frequências da variável "VO2" em repouso e no pico do exercício para pacientes classificados em cada um dos níveis da variável "Etiologia" por meio de gráficos QQ e de medidas resumo. Comente os resultados.
  
#### Resolução

b) Repita o item a) utilizando gráficos de Bland-Altman.
  
#### Resolução

c) Utilize \textit{boxplots} e gráficos de perfis médios para comparar as distribuições da variável "Frequência cardíaca" correspondentes a pacientes nos diferentes níveis da variável "NYHA". Comente os resultados.

#### Resolução

### Exercício 7

Considere os dados do arquivo \textit{figadodiag}. Calcule a sensibilidade, especificidade, taxas de falsos positivos e falsos negativos e acurácia das técnicas radiológicas para detecção de alterações anatômicas tendo os resultados intraoperatórios como padrão áureo.

#### Resolução

### Exercício 12

Prove que $$r_\rho = \frac{\sum_{i=1}^{n} (x_i - \overline{x}) \cdot(y_i - \overline{y})}{[\sum_{i=1}^{n} (x_i - \overline{x})^{2} \cdot \sum_{i=1}^{n}(y_i - \overline{y})^{2}]^{\frac{1}{2}}}$$ e $$ r_\rho = \frac{\sum_{i=1}^{n} (x_i \cdot y_i - n \cdot \overline{x} \cdot \overline{y}) }{[\sum_{i=1}^{n} (x_i^{2} - \overline{x}^{2})\cdot \sum_{i=1}^{n}(y_i^{2} - \overline{y}^{2})]^{\frac{1}{2}}}$$ são equivalentes.

#### Resolução

### Exercício 14

Os dados da Tabela 4.24 são provenientes de um estudo em que um dos objetivos era avaliar o efeito da dose de radiação gama (em centigrays) na formação de múltiplos micronúcleos em células de indivíduos normais. Analise os dados descritivamente, calculando o risco relativo de ocorrência de micronúcleos para cada dose tomando como base a dose nula. Repita a análise calculando as razões de chances correspondentes. Qual as conclusões de suas análises?

\begin{table}[H]
\centering
\caption{Tabela 4.24: Número de células}
\begin{tabular}{ccc}
\hline
Dose de radiação gama (cGy) & Frequência de células com múltiplos micronúcleos & Total de células examinadas \\ \hline
0 & 1 & 2373 \\
20 & 6 & 2662 \\
50 & 25 & 1991 \\
100 & 47 & 2047 \\
200 & 82 & 2661 \\
300 & 207 & 2442 \\
400 & 254 & 2398 \\
500 & 285 & 1746 \\
\hline
\end{tabular}
\end{table}

#### Resolução

### Exercício 19

Para avaliar a associação entre a persistência do canal arterial (PCA) em récem-nascidos pré termo (RNPT) e óbito ou hemorragia intercraniana, um pesquisador obteve os dados dispostos na seguinte tabela 

\begin{table}[H]
\centering
\caption{Frequências absolutas e relativas de óbitos e hemorragia intracraniana em récem-nascidos}
\begin{tabular}{ccccccc}
\hline
PCA & \multicolumn{3}{c}{Óbito} & \multicolumn{3}{c}{Hemorragia intracraniana} \\ \hline
& Sim & Não & Total & Sim & Não & Total \\ \hline
Presente & 8 & 13 & 21 & 7 & 14 & 21 \\
Ausente & 1 & 39 & 40 & 7 & 33 & 40 \\ \hline
Total & 9 & 52 & 61 & 14 & 47 & 61 \\
\hline
\end{tabular}
\end{table}

Um resumo das análises para óbitos e hemorragia intracraniana está disposto na tabeka seguinte

\begin{table}[H]
\centering
\begin{tabular}{ccccc}
\hline
& & \multicolumn{3}{c}{Razão de chances e Intervalo de Confiança (95\%)}  \\ \hline
Variável & valor p & Estimativa & Lim inf & Lim sup\\ \hline
Óbito & 0,001 & 24,0 & 2,7 & 210,5 \\
Hemorragia intracraniana & 0,162 & 2,4 & 0,7 & 8,0\\ 
\hline
\end{tabular}
\end{table}

a) Interprete as estimativas das razões de chances, indicando claramente a que paciente elas se referem.

#### Resolução

b) Analogamente, interprete os intervalos de confiança correspondentes, indicando claramente a que pacientes eles se referem.

#### Resolução

c) Com base nos resultados anteriores, o que você concluir sobre a associação entre persistência do canal arterial e óbito para RNTP em geral? E sobre a associação entre a persistência do canal arterial e a ocorrência de hemorragia interna? Justifique suas respostas.

#### Resolução

d) Qual é a hipótese nula testada em cada caso? 

#### Resolução 

e) Qual é a interpretação dos níveis descritivos (p-value) em cada caso?

#### Resolução

Detalhes podem ser obtidos em Afiune (2000).

### Exercício 23

Considere os dados do arquivo \textit{entrevista}. Calcule estatísticas $\kappa$ sem e com ponderação para quantificar a concordância entre as duas observações (G e P) para as variáveis "Impacto" e "Independência" e comente os resultados.

#### Resolução